networks:
  backend:
    driver: bridge

services:
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/todo
    ports:
      - "3000:80"
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/todos"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5